# dataset
image_train_dir: "../data/train_images"
mask_train_dir: "../data/train_labels"
image_val_dir: "../data/test_images"
mask_val_dir: "../data/test_labels"
channel: 1 # Blue most relevent
img_size: 512
apply_repeat: true
apply_clahe: true
batch_size: 16

# model
model_name: "nvidia/segformer-b1-finetuned-ade-512-512" 
num_labels: 1

# training layer : "segformer.encoder.patch_embeddings 0-3", "segformer.encoder.block.0 - 3", "decode_head"
frozen_layers : ["segformer.encoder.patch_embeddings.0",    "segformer.encoder.patch_embeddings.1",
                  "segformer.encoder.block.0", "segformer.encoder.block.1"]